load("//tensorflow:tensorflow.bzl", "tf_cc_binary")


tf_cc_binary(
    name = "Othello_LTBeL",
    srcs = ["Othello_LTBeL.cc"],
    deps = [
        "//tensorflow/cc:cc_ops",
        "//tensorflow/cc:client_session",
        "//tensorflow/core:tensorflow",
    ],
)
